(cl:defpackage lidar_tracker-msg
  (:use )
  (:export
   "<VSCAN_TRACKED>"
   "VSCAN_TRACKED"
   "<DETECTEDOBJECTARRAY>"
   "DETECTEDOBJECTARRAY"
   "<GEOMETRIC_RECTANGLE>"
   "GEOMETRIC_RECTANGLE"
   "<VSCAN_TRACKED_ARRAY>"
   "VSCAN_TRACKED_ARRAY"
   "<CLOUDCLUSTERARRAY>"
   "CLOUDCLUSTERARRAY"
   "<CLOUDCLUSTER>"
   "CLOUDCLUSTER"
   "<DETECTEDOBJECT>"
   "DETECTEDOBJECT"
   "<CENTROIDS>"
   "CENTROIDS"
  ))

