// Generated by gencpp from file cv_tracker_msgs/obj_label.msg
// DO NOT EDIT!


#ifndef CV_TRACKER_MSGS_MESSAGE_OBJ_LABEL_H
#define CV_TRACKER_MSGS_MESSAGE_OBJ_LABEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace cv_tracker_msgs
{
template <class ContainerAllocator>
struct obj_label_
{
  typedef obj_label_<ContainerAllocator> Type;

  obj_label_()
    : header()
    , type()
    , obj_id()
    , reprojected_pos()  {
    }
  obj_label_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(_alloc)
    , obj_id(_alloc)
    , reprojected_pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _obj_id_type;
  _obj_id_type obj_id;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _reprojected_pos_type;
  _reprojected_pos_type reprojected_pos;




  typedef boost::shared_ptr< ::cv_tracker_msgs::obj_label_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cv_tracker_msgs::obj_label_<ContainerAllocator> const> ConstPtr;

}; // struct obj_label_

typedef ::cv_tracker_msgs::obj_label_<std::allocator<void> > obj_label;

typedef boost::shared_ptr< ::cv_tracker_msgs::obj_label > obj_labelPtr;
typedef boost::shared_ptr< ::cv_tracker_msgs::obj_label const> obj_labelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cv_tracker_msgs::obj_label_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cv_tracker_msgs::obj_label_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cv_tracker_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'cv_tracker_msgs': ['/home/wenws/10_NLOS_Correction_/src/cv_tracker_msgs/msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cv_tracker_msgs::obj_label_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cv_tracker_msgs::obj_label_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cv_tracker_msgs::obj_label_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cv_tracker_msgs::obj_label_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cv_tracker_msgs::obj_label_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cv_tracker_msgs::obj_label_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cv_tracker_msgs::obj_label_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1908c8a3e1598adc90838e6b6436a771";
  }

  static const char* value(const ::cv_tracker_msgs::obj_label_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1908c8a3e1598adcULL;
  static const uint64_t static_value2 = 0x90838e6b6436a771ULL;
};

template<class ContainerAllocator>
struct DataType< ::cv_tracker_msgs::obj_label_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cv_tracker_msgs/obj_label";
  }

  static const char* value(const ::cv_tracker_msgs::obj_label_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cv_tracker_msgs::obj_label_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string type\n\
int32[] obj_id\n\
geometry_msgs/Point[] reprojected_pos\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::cv_tracker_msgs::obj_label_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cv_tracker_msgs::obj_label_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.obj_id);
      stream.next(m.reprojected_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obj_label_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cv_tracker_msgs::obj_label_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cv_tracker_msgs::obj_label_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "obj_id[]" << std::endl;
    for (size_t i = 0; i < v.obj_id.size(); ++i)
    {
      s << indent << "  obj_id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.obj_id[i]);
    }
    s << indent << "reprojected_pos[]" << std::endl;
    for (size_t i = 0; i < v.reprojected_pos.size(); ++i)
    {
      s << indent << "  reprojected_pos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.reprojected_pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CV_TRACKER_MSGS_MESSAGE_OBJ_LABEL_H
