(cl:in-package nlosExclusion-msg)
(cl:export '(GNSS_TIME-VAL
          GNSS_TIME
          TOTAL_SV-VAL
          TOTAL_SV
          PRN_SATELLITES_INDEX-VAL
          PRN_SATELLITES_INDEX
          PSEUDORANGE-VAL
          PSEUDORANGE
          SNR-VAL
          SNR
          ELEVATION-VAL
          ELEVATION
          AZIMUTH-VAL
          AZIMUTH
          ERR_TROPO-VAL
          ERR_TROPO
          ERR_IONO-VAL
          ERR_IONO
          SAT_CLK_ERR-VAL
          SAT_CLK_ERR
          SAT_POS_X-VAL
          SAT_POS_X
          SAT_POS_Y-VAL
          SAT_POS_Y
          SAT_POS_Z-VAL
          SAT_POS_Z
          VISABLE-VAL
          VISABLE
          SAT_SYSTEM-VAL
          SAT_SYSTEM
))