// Generated by gencpp from file nlosExclusion/GNSS_Raw_Array.msg
// DO NOT EDIT!


#ifndef NLOSEXCLUSION_MESSAGE_GNSS_RAW_ARRAY_H
#define NLOSEXCLUSION_MESSAGE_GNSS_RAW_ARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nlosExclusion/GNSS_Raw.h>

namespace nlosExclusion
{
template <class ContainerAllocator>
struct GNSS_Raw_Array_
{
  typedef GNSS_Raw_Array_<ContainerAllocator> Type;

  GNSS_Raw_Array_()
    : header()
    , GNSS_Raws()  {
    }
  GNSS_Raw_Array_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , GNSS_Raws(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::nlosExclusion::GNSS_Raw_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nlosExclusion::GNSS_Raw_<ContainerAllocator> >::other >  _GNSS_Raws_type;
  _GNSS_Raws_type GNSS_Raws;




  typedef boost::shared_ptr< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> const> ConstPtr;

}; // struct GNSS_Raw_Array_

typedef ::nlosExclusion::GNSS_Raw_Array_<std::allocator<void> > GNSS_Raw_Array;

typedef boost::shared_ptr< ::nlosExclusion::GNSS_Raw_Array > GNSS_Raw_ArrayPtr;
typedef boost::shared_ptr< ::nlosExclusion::GNSS_Raw_Array const> GNSS_Raw_ArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nlosExclusion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'nlosExclusion': ['/home/wenws/10_NLOS_Correction_/src/nlosExclusion/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8eb26aafb0dddf7c59548e059be439ec";
  }

  static const char* value(const ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8eb26aafb0dddf7cULL;
  static const uint64_t static_value2 = 0x59548e059be439ecULL;
};

template<class ContainerAllocator>
struct DataType< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlosExclusion/GNSS_Raw_Array";
  }

  static const char* value(const ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
nlosExclusion/GNSS_Raw[] GNSS_Raws\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nlosExclusion/GNSS_Raw\n\
float64 GNSS_time\n\
float64 total_sv\n\
float64 prn_satellites_index\n\
float64 pseudorange\n\
float64 snr\n\
float64 elevation\n\
float64 azimuth\n\
float64 err_tropo\n\
float64 err_iono\n\
float64 sat_clk_err\n\
float64 sat_pos_x\n\
float64 sat_pos_y\n\
float64 sat_pos_z\n\
int64 visable #0-Not sure 1-visable 2-invisable\n\
string  sat_system\n\
";
  }

  static const char* value(const ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.GNSS_Raws);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GNSS_Raw_Array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlosExclusion::GNSS_Raw_Array_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "GNSS_Raws[]" << std::endl;
    for (size_t i = 0; i < v.GNSS_Raws.size(); ++i)
    {
      s << indent << "  GNSS_Raws[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nlosExclusion::GNSS_Raw_<ContainerAllocator> >::stream(s, indent + "    ", v.GNSS_Raws[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLOSEXCLUSION_MESSAGE_GNSS_RAW_ARRAY_H
